### ISSUE TITLE
`login` succeeds, `status` fails

### ISSUE THREAD

**Issue by pjboro** [mightymatth/arcli#2]
Hi.

I've just build and tried arcli and I have some troubles. I'm not sure what's wrong.

```
╭─pjb@dishwasher ~/git/arcli ‹master*› 
╰─$ ./arcli login                 
Hostname (dishwasher): my-redmine.hostname.com
Username: piotr.borowski                                                 
Password:                           
You have successfully logged in!
╭─pjb@dishwasher ~/git/arcli ‹master*› 
╰─$ ./arcli status
Cannot fetch user.
PERIOD       HOURS   H/LOG   # of I   # of P  
Today        ERR
Yesterday    ERR
This Week    ERR
Last Week    ERR
This Month   ERR
Last Month   ERR
Failed to get status: cannot get period data (lw): Get https://dishwasher/time_entries.json?spent_on=lw&user_id=me&limit=200: dial tcp [fe80::42:5
0ff:fef4:5643%docker0]:443: connect: connection refused
```
If I understand correctly it tries to send a get request to localhost (`Failed to get status: cannot get period data (lw): Get https://MY_HOSTNAME`). Have you experienced similar issues? It's really strange, because previous request, the login, works just fine.

Regards!

**Comment by mightymatth** [comment]
I apologise for late response. Thank for trying out arcli.

Your issue is probably caused by not serving your redmine server over https. Well, due to security concerns, arcli will only connect via https. Try setting up your redmine server locally (e.g. via docker), then setup ngrok tunnel to your local server (`ngrok http 8080`). This will give you https endpoint of your local server. Tell me if this helps.

**Comment by pjboro** [comment]
> I apologise for late response. Thanks for trying out arcli.
Sure, it's totally fine.

>Your issue is probably caused by not serving your redmine server over https
It is certainly served over https. I tried to specify the protocol when entering domain name, but it hasn't change anything.

The last part of the log seems strange: it seems like trying to send the request to localhost instead of the remote host I specified (`my-redmine.hostname.com`). I did not look in the code, as my Go skills are almost non-existent.

**Comment by mightymatth** [comment]
I am not able to fully reproduce your case. I've tried, but on my system, everything seems ok.

However, it might be that you entered your hostname first time as `dishwasher` and you logged in with your username and password successfully. After a successful login, the hostname will be written in `.arcli.yaml` file inside your home directory. That's why you see dishwasher in parenthesis here:

```
Hostname (dishwasher): my-redmine.hostname.com
```

If you leave this empty, the value inside parenthesis will be used as your hostname.
What might happen is that your new hostname couldn't be written to `.arcli.yaml` file. I'm just guessing.

Please provide me more information about your setup; how did you install arcli, what's your system information (OS).

**Comment by mdschmitt** [comment]
I was running into something similar, though not quite the same.  I was getting a ton of errors involving some form of `unsupported protocol scheme ""`.  Turns out, the line [here](https://github.com/mightymatth/arcli/blob/59d09e5850e15062425e157b6ce49664be4506d5/client/client.go#L160) respects _environment variables_ **OVER** the contents of `~/.arcli.yaml`.  
```golang
host = viper.GetString(config.Host)
```
Thus, the problem (for me) was the following line in my `~/.zshrc`:
```bash
HOST="$(hostname)"
```
`unset HOST` and/or deleting/commenting-out that line fixed everything.

Leaving this here in case others run into similar issues and are bashing their heads against it like I did.
