### ISSUE TITLE
Allow self signed certificate

### ISSUE THREAD

**Issue by gyhor** [mightymatth/arcli#4]
Login is not possible, if certificate is self signed

User response: Get https://username:***@xxxxxxx/users/current.json: x509: certificate signed by unknown authority

**Comment by mightymatth** [comment]
@gyhor, it's enforced to use the Redmine server with an SSL certificate because you are sending username/password in plain text. If you are running this locally, you can try to tunnel your server through [ngrok](https://ngrok.com/). 
For example, if your server is hosted on `http://localhost:3000`, you would run `ngrok http 3000` and receive an HTTPS link, e.g. `https://8d8cf15bc0e2.ngrok.io/`. This way, you won't have issues with the certificate.
I'll maybe enable a flag to allow insecure communication.
Tell me if it helps.

**Comment by gyhor** [comment]
thank you for the fast response. The redmine server does have a SSL certificate. The thing is that it is self signed from our company.
so ssl is active and username/password is crypted. 
Maybe it is possible to implement a parameter for allowing self signed certificate like in curl?

**Comment by mightymatth** [comment]
Sure, I'll support that!

**Comment by mightymatth** [comment]
@gyhor can you checkout #18 branch and check how it works on your Redmine server?

**Comment by gyhor** [comment]
Thank you! I couldn't test it, because I am using the snap version. Tonight I am trying the dev version.

**Comment by mightymatth** [comment]
Now you can update to the latest version via brew or snapcraft. (0.3.8)
